### ISSUE TITLE
invalid base 64 characters when using token based authentication

### ISSUE THREAD

**Issue by JefeDavis** [felixfbecker/PSKubectl#25]
getting the error `The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or a non-white space character among the padding characters` when using config file generated via rancher using token based authentication

kubectl.exe works perfectly fine but I am unable to use any pskubectl cmdlets

**Comment by felixfbecker** [comment]
Hmm this is hard to debug without having the config file. Can you reproduce it with a similar file that wouldn't give away actual credentials?
