### ISSUE TITLE
Make module compatible for any version of PSCore by targeting netstandard2.0

### ISSUE THREAD

**Issue by bergmeister** [felixfbecker/PSKubectl#30]
Is there a reason for not using .Net Standard or are there any other blockers in terms of dependencies? I see there are 8 .Net Apis that are not part of the standard but I am sure we could use alternative ones for the same behaviour.

**Comment by felixfbecker** [comment]
I _think_ there was some dependency that only worked with PSCore but I don't remember any more. I'm not super familiar with the whole .NET stuff so I'd be happy to review a PR

**Comment by felixfbecker** [comment]
I think it was `Microsoft.AspNetCore.JsonPatch`. However my current plan is to only support server-side apply, so that wouldn't be needed anymore

**Comment by felixfbecker** [comment]
Looks like we are targeting this now
