### ISSUE TITLE
Implement creating resources with Update-KubeResource

### ISSUE THREAD

**Issue by felixfbecker** [felixfbecker/PSKubectl#8]
It currently only handles patches

**Comment by MortenMeisler** [comment]
yes! Upvote. I can see you are using the `client.Dynamic().Patch` method from KubeClient, any plan to make the same functionality for Create? Or would that require that the KubeClient library have the same kind of dynamic interface for patch? 

It seems like the method is strongly typed, ex.:
`await client.DeploymentsV1().Create(deploymentV1);`
would be nice to have support for dynamic as well or make a generic function. I'm probably not sharp enough on the c# for that..would it be possible to extend the method somehow?

**Comment by felixfbecker** [comment]
I am not 100% sure but I think with server-side apply, sending a PATCH for a non-existent resource should create it. Otherwise the dynamic client would need to receive support for `Create` which doesn't seem difficult (cc @tintoy).

The first useful step would be to write a Pester test that calls `Update-KubeResource` on a non-existent resource and asserts it's being created.

**Comment by MortenMeisler** [comment]
Alright thanks for the answer, you know when this is coming? I saw various posts on alpha/beta release, but we're using AKS which is running Kubernetes 1.14 atm.

**Comment by tintoy** [comment]
Yeah I think this depends on the semantics for server-side apply. I’ll have a look when I get home :)
